name: DeepSeek Code Reviewer

on:
  pull_requests:
    branches: ["main", "develop"]

jobs:
  code-review:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Python setup
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run DS code reviewer
        env:
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
        run: |
          python .github/scripts/deepseek_review.py
